export const dataBestSeller=[
    {
        id:1,
        title:"tokyo purpel",
        price:"100",
        category:"masseuse",
        linking:"/images/tab1.png"
    },
    {
        id:2,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab2.png"
    },
    {
        id:3,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab3.png"
    },
    {
        id:4,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab4.png"
    },
    {
        id:5,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab5.png"
    },
    {
        id:6,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab6.png"
    },
    {
        id:7,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab7.png"
    },
    {
        id:8,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab8.png"
    },
    {
        id:8,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab18.png"
    },{
        id:8,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab19.png"
    },{
        id:8,
        title:"nom",
        price:"100",
        category:"masseuse",
        linking:"/images/tab20.png"
    },
]